void carregarArquivo(char path[]);
int buscarElemento(int vet[], int n, int opc, int x);
void ordernarDados(int vet[], int n);
void gerarRelatorio();
void BubbleSort(int vet[], int n);
void InsertSort (int vet[], int n);
void SelectionSort(int vet[], int n);
void MergeSort(int vet[], int inicio, int fim);
void Merge(int vet[], int inicio, int meio, int fim);
void QuickSort(int vet[], int inicio, int fim);
int Particiona(int vet[], int inicio, int fim);
void troca(int *a, int *b);